### ISSUE TITLE
has error in ubuntu but correctly run on the wiondows 

### ISSUE THREAD

**Issue by erfangian** [soskek/convolutional_seq2seq#3]
thanks for sharing this code .
i run the code on the windows and correctly run .
now i want to run this code on the ubuntu server but i get this error ..

chainer.utils.type_check.InvalidType:
Invalid operation is performed in: EmbedIDFunction (Forward)

Expect: in_types[0].dtype == <class 'numpy.int32'>
Actual: int64 != <class 'numpy.int32'>

**Comment by erfangian** [comment]
please help me .. how can i fix this error

**Comment by niboshi** [comment]
Duplicated: https://github.com/chainer/chainer/issues/3288

**Comment by erfangian** [comment]
Thank you for your reply

**Comment by erfangian** [comment]
i fix this error in chainer/chainer#3288
